export interface AirportOption {
  label: string;
  value: string;
}

export const SUPPORTED_AIRPORTS: AirportOption[] = [
  { label: 'ANC - Anchorage', value: 'ANC' },
  { label: 'ATL - Atlanta', value: 'ATL' },
  { label: 'AUS - Austin', value: 'AUS' },
  { label: 'BHZ - Belo Horizonte', value: 'BHZ' },
  { label: 'BJS - Beijing', value: 'BJS' },
  { label: 'BLR - Bangalore', value: 'BLR' },
  { label: 'BNA - Nashville', value: 'BNA' },
  { label: 'BOG - Bogota', value: 'BOG' },
  { label: 'BOM - Mumbai', value: 'BOM' },
  { label: 'BOS - Boston', value: 'BOS' },
  { label: 'BUF - Buffalo', value: 'BUF' },
  { label: 'CHI - Chicago', value: 'CHI' },
  { label: 'CLE - Cleveland', value: 'CLE' },
  { label: 'CLT - Charlotte', value: 'CLT' },
  { label: 'CMH - Columbus', value: 'CMH' },
  { label: 'CVG - Cincinnati', value: 'CVG' },
  { label: 'DAY - Dayton', value: 'DAY' },
  { label: 'DEL - Delhi', value: 'DEL' },
  { label: 'DEN - Denver', value: 'DEN' },
  { label: 'DFW - Dallas/Fort Worth', value: 'DFW' },
  { label: 'DTT - Detroit', value: 'DTT' },
  { label: 'FLL - Fort Lauderdale', value: 'FLL' },
  { label: 'FRA - Frankfurt', value: 'FRA' },
  { label: 'GSP - Greenville', value: 'GSP' },
  { label: 'HOU - Houston', value: 'HOU' },
  { label: 'JAX - Jacksonville', value: 'JAX' },
  { label: 'LAS - Las Vegas', value: 'LAS' },
  { label: 'LAX - Los Angeles', value: 'LAX' },
  { label: 'LED - St. Petersburg', value: 'LED' },
  { label: 'LGB - Long Beach', value: 'LGB' },
  { label: 'LON - London', value: 'LON' },
  { label: 'MAD - Madrid', value: 'MAD' },
  { label: 'MIA - Miami', value: 'MIA' },
  { label: 'MKC - Kansas City', value: 'MKC' },
  { label: 'MKE - Milwaukee', value: 'MKE' },
  { label: 'MOW - Moscow', value: 'MOW' },
  { label: 'MSP - Minneapolis/St. Paul', value: 'MSP' },
  { label: 'MUC - Munich', value: 'MUC' },
  { label: 'NCE - Nice', value: 'NCE' },
  { label: 'NYC - New York City', value: 'NYC' },
  { label: 'OAK - Oakland', value: 'OAK' },
  { label: 'OKC - Oklahoma City', value: 'OKC' },
  { label: 'OMA - Omaha', value: 'OMA' },
  { label: 'ONT - Ontario', value: 'ONT' },
  { label: 'ORF - Norfolk', value: 'ORF' },
  { label: 'ORL - Orlando', value: 'ORL' },
  { label: 'PAR - Paris', value: 'PAR' },
  { label: 'PBI - West Palm Beach', value: 'PBI' },
  { label: 'PDX - Portland', value: 'PDX' },
  { label: 'PHL - Philadelphia', value: 'PHL' },
  { label: 'PHX - Phoenix', value: 'PHX' },
  { label: 'PIT - Pittsburgh', value: 'PIT' },
  { label: 'RDU - Raleigh/Durham', value: 'RDU' },
  { label: 'RIO - Rio de Janeiro', value: 'RIO' },
  { label: 'SAN - San Diego', value: 'SAN' },
  { label: 'SAO - Sao Paulo', value: 'SAO' },
  { label: 'SCL - Santiago', value: 'SCL' },
  { label: 'SEA - Seattle', value: 'SEA' },
  { label: 'SFO - San Francisco', value: 'SFO' },
  { label: 'SHA - Shanghai', value: 'SHA' },
  { label: 'SJC - San Jose', value: 'SJC' },
  { label: 'SLC - Salt Lake City', value: 'SLC' },
  { label: 'SNA - Santa Ana', value: 'SNA' },
  { label: 'SSA - Salvador', value: 'SSA' },
  { label: 'STL - St. Louis', value: 'STL' },
  { label: 'SYD - Sydney', value: 'SYD' },
  { label: 'TPA - Tampa', value: 'TPA' },
  { label: 'WAS - Washington', value: 'WAS' },
  { label: 'YHZ - Halifax', value: 'YHZ' },
  { label: 'YLW - Kelowna', value: 'YLW' },
  { label: 'YMQ - Montreal', value: 'YMQ' },
  { label: 'YOW - Ottawa', value: 'YOW' },
  { label: 'YQB - Quebec City', value: 'YQB' },
  { label: 'YQR - Regina', value: 'YQR' },
  { label: 'YTO - Toronto', value: 'YTO' },
  { label: 'YVR - Vancouver', value: 'YVR' },
  { label: 'YWG - Winnipeg', value: 'YWG' },
  { label: 'YXE - Saskatoon', value: 'YXE' },
  { label: 'YYC - Calgary', value: 'YYC' },
  { label: 'YYJ - Victoria', value: 'YYJ' },
].sort((a, b) => a.label.localeCompare(b.label));
